sudo: required

language: java
jdk:
  - oraclejdk8

before_cache:
  - rm -fr /home/travis/.m2/repository/webdriver/

addons:
  apt:
    update: true
  chrome: stable

before_install:
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - export CHROME_BIN=/usr/bin/google-chrome

install: true

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5